configfile: "config/config.yaml"

if ".gz" in config["input_fastq"]:
    compressed = True
else:
    compressed = False

rule all:
    input:
        assigned_barcodes=expand("{save_path}/demultiplex_data/dorado{score}_O{O}_E{E}/assigned_barcodes.txt",
                    save_path=config["save_path"],
                    score=config["scoring_options"],
                    O=config["overlap"],
                    E=config["error_rate"]),
        entropy_plot=expand("{save_path}/demultiplex_data/dorado{score}_O{O}_E{E}/entropy_dist.png",
                            save_path=config["save_path"],
                            score=config["scoring_options"],
                            O=config["overlap"],
                            E=config["error_rate"]),
        barcode_plot=expand("{save_path}/demultiplex_data/dorado{score}_O{O}_E{E}/barcode_frac.png",
                            save_path=config["save_path"],
                            score=config["scoring_options"],
                            O=config["overlap"],
                            E=config["error_rate"]),
        classifications=expand("{save_path}/demultiplex_data/dorado{score}_O{O}_E{E}/classifications.txt",
                    save_path=config["save_path"],
                    score=config["scoring_options"],
                    O=config["overlap"],
                    E=config["error_rate"]),
        tool_stats=expand("{save_path}/demultiplex_data/dorado{score}_O{O}_E{E}/tool_stats.txt",
                    save_path=config["save_path"],
                    score=config["scoring_options"],
                    O=config["overlap"],
                    E=config["error_rate"]),
        tool_stats_plot=expand("{save_path}/demultiplex_data/dorado{score}_O{O}_E{E}/tool_stats_plot.png",
                    save_path=config["save_path"],
                    score=config["scoring_options"],
                    O=config["overlap"],
                    E=config["error_rate"]),
        assigned_barcodes_nounclassified=expand("{save_path}/demultiplex_data/no_unclassified/dorado{score}_O{O}_E{E}/assigned_barcodes.txt",
                            save_path=config["save_path"],
                            score=config["scoring_options"],
                            O=config["overlap"],
                            E=config["error_rate"]),
        entropy_plot_nounclassified=expand("{save_path}/demultiplex_data/no_unclassified/dorado{score}_O{O}_E{E}/entropy_dist.png",
                            save_path=config["save_path"],
                            score=config["scoring_options"],
                            O=config["overlap"],
                            E=config["error_rate"]),
        barcode_plot_nounclassified=expand("{save_path}/demultiplex_data/no_unclassified/dorado{score}_O{O}_E{E}/barcode_frac.png",
                            save_path=config["save_path"],
                            score=config["scoring_options"],
                            O=config["overlap"],
                            E=config["error_rate"]),
        classifications_nounclassified=expand("{save_path}/demultiplex_data/no_unclassified/dorado{score}_O{O}_E{E}/classifications.txt",
                            save_path=config["save_path"],
                            score=config["scoring_options"],
                            O=config["overlap"],
                            E=config["error_rate"]),
        classified_reads=expand("{save_path}/classified_reads/{barcodes_final}.fastq",
                            save_path=config["save_path"],
                            barcodes_final=config["barcodes_nounclassified"])

# perform classifications with cutadapt
rule cutadapt:
    input:
        fastq=config["input_fastq"],
        barcodes="resources/custom_arrangements/{location}.fasta"
    output:
        "results/dorado{score}_O{O}_E{E}/cutadapt/{location}/{barcode_name}"
    params:
        O=config["overlap"],
        E=config["error_rate"]
    conda:
        "envs/cutadapt.yaml"
    script:
        "scripts/cutadapt_processing.py"

# perform classifications with dorado
rule dorado_demux:
    input: 
        fastq=config["input_fastq"],
        barcodes="resources/barcodes.fasta",
        barcodes_reversed="resources/barcodes_rev.fasta"
    output:
        "results/dorado{score}_O{O}_E{E}/dorado/{location}/unclassified.fastq"
    params:
        score=config["scoring_options"]
    conda:
        "envs/dorado.yaml"
    script:
        "scripts/dorado_processing.py"

# assign classificaiton on base of entropy and create various summary statistics plots
rule get_classifications:
    input:
        cutadapt_input=expand("results/dorado{score}_O{O}_E{E}/cutadapt/{location}/{barcode_name}",
                                location=config["barcode_locations"],
                                barcode_name=config["barcode_names"],
                                score=config["scoring_options"],
                                O=config["overlap"],
                                E=config["error_rate"]),
        dorado_input=expand("results/dorado{score}_O{O}_E{E}/dorado/{location}/unclassified.fastq",
                            location=config["barcode_locations"],
                            score=config["scoring_options"],
                            O=config["overlap"],
                            E=config["error_rate"])
    output:
        assigned_barcodes=expand("{save_path}/demultiplex_data/dorado{score}_O{O}_E{E}/assigned_barcodes.txt",
                    save_path=config["save_path"],
                    score=config["scoring_options"],
                    O=config["overlap"],
                    E=config["error_rate"]),
        entropy_plot=expand("{save_path}/demultiplex_data/dorado{score}_O{O}_E{E}/entropy_dist.png",
                            save_path=config["save_path"],
                            score=config["scoring_options"],
                            O=config["overlap"],
                            E=config["error_rate"]),
        barcode_plot=expand("{save_path}/demultiplex_data/dorado{score}_O{O}_E{E}/barcode_frac.png",
                            save_path=config["save_path"],
                            score=config["scoring_options"],
                            O=config["overlap"],
                            E=config["error_rate"]),
        classifications=expand("{save_path}/demultiplex_data/dorado{score}_O{O}_E{E}/classifications.txt",
                    save_path=config["save_path"],
                    score=config["scoring_options"],
                    O=config["overlap"],
                    E=config["error_rate"]),
        tool_stats=expand("{save_path}/demultiplex_data/dorado{score}_O{O}_E{E}/tool_stats.txt",
                    save_path=config["save_path"],
                    score=config["scoring_options"],
                    O=config["overlap"],
                    E=config["error_rate"]),
        tool_stats_plot=expand("{save_path}/demultiplex_data/dorado{score}_O{O}_E{E}/tool_stats_plot.png",
                    save_path=config["save_path"],
                    score=config["scoring_options"],
                    O=config["overlap"],
                    E=config["error_rate"]),
        assigned_barcodes_nounclassified=expand("{save_path}/demultiplex_data/no_unclassified/dorado{score}_O{O}_E{E}/assigned_barcodes.txt",
                            save_path=config["save_path"],
                            score=config["scoring_options"],
                            O=config["overlap"],
                            E=config["error_rate"]),
        entropy_plot_nounclassified=expand("{save_path}/demultiplex_data/no_unclassified/dorado{score}_O{O}_E{E}/entropy_dist.png",
                            save_path=config["save_path"],
                            score=config["scoring_options"],
                            O=config["overlap"],
                            E=config["error_rate"]),
        barcode_plot_nounclassified=expand("{save_path}/demultiplex_data/no_unclassified/dorado{score}_O{O}_E{E}/barcode_frac.png",
                            save_path=config["save_path"],
                            score=config["scoring_options"],
                            O=config["overlap"],
                            E=config["error_rate"]),
        classifications_nounclassified=expand("{save_path}/demultiplex_data/no_unclassified/dorado{score}_O{O}_E{E}/classifications.txt",
                            save_path=config["save_path"],
                            score=config["scoring_options"],
                            O=config["overlap"],
                            E=config["error_rate"])
    conda:
        "envs/get_classifications.yaml"
    script:
        "scripts/make_tables_nounclassified.py"

# split reads from original .fastq file into folders according to classification
rule classify_reads:
    input:
        fastq=config["input_fastq"],
        classifications=expand("{save_path}/demultiplex_data/no_unclassified/dorado{score}_O{O}_E{E}/classifications.txt",
                            save_path=config["save_path"],
                            score=config["scoring_options"],
                            O=config["overlap"],
                            E=config["error_rate"]),
        assigned_barcodes=expand("{save_path}/demultiplex_data/no_unclassified/dorado{score}_O{O}_E{E}/assigned_barcodes.txt",
                            save_path=config["save_path"],
                            score=config["scoring_options"],
                            O=config["overlap"],
                            E=config["error_rate"])
    output:
        expand("{save_path}/classified_reads/{barcodes_final}.fastq",
            save_path=config["save_path"],
            barcodes_final = config["barcodes_nounclassified"])
    params:
        output_dir=config["save_path"],
        compressed=compressed
    conda:
        "envs/get_classifications.yaml"
    script:
        "scripts/classify_reads.py"